all:
	g++ Slicing_Annealer.cpp -std=c++11 -o Slicing_Annealer.out

clean:
	rm Slicing_Annealer.out Slicing_Annealer.h.gch .Slicing_Annealer.h.swp .Slicing_Annealer.cpp.swp

run: all 
	./Slicing_Annealer.out
